#!/usr/bin/env bash

typewriter() {
    local text="$1"
    local delay="0.03"
    for ((i=0; i<${#text}; i++)); do
        printf "%s" "${text:$i:1}"
        sleep "$delay"
    done
    printf "\n"
}
     
 #validation block
if [ "$EUID" -ne 0 ]; then
    echo "Error: This installer needs to be run as root."
    exit1
fi

if ! command -v systemctl >/dev/null 2>&1; then
    echo "Error: systemd is not available on this system."
    exit1
fi

 #installation block

TIMEZONE_CHOICES=(
    "Africa/Cairo"
    "America/New_York"
    "America/Los_Angeles"
    "America/Sao_Paulo"
    "Asia/Dubai"
    "Asia/Hong_Kong"
    "Asia/Kolkata"
    "Asia/Tokyo"
    "Australia/Sydney"
    "Europe/Berlin"
    "Europe/London"
    "Europe/Moscow"
    "Europe/Paris"
    "Pacific/Auckland"
    "Pacific/Honolulu"
)

CONFIG_FILE="/etc/vpn-tz.conf"

#create conf file
write_config() {
    local tz="$1"
    mkdir -p "$(dirname "$CONFIG_FILE")"
    tee "$CONFIG_FILE" > /dev/null <<EOF
# Generated by the vpn‑tz installer – edit with care.
DEFAULT_TZ=$tz
EOF
    echo "Default timezone saved as \"$tz\" in $CONFIG_FILE"
}
#-abort helper 
abort_install() {
    echo "✖️  Installation aborted."
    exit 1
}

#interactive mode
run_interactive() {
    if ! [[ -t 0 && -t 1 ]]; then
         echo "No interactive terminal available - cannot continue."
         abort_install
    fi

    echo "Please select your preferred *default* timezone. This will be used as a fallback to the original system."
    for i in "${!TIMEZONE_CHOICES[@]}"; do
        printf " %2d) %s\n" "$((i+1))" "${TIMEZONE_CHOICES[$i]}"
    done
    while true; do
        read -rp "Enter the number (1-${#TIMEZONE_CHOICES[@]}) or press Ctrl-C to abort: " choice
        [[ -z "$choice" ]] && abort_install

        choice="${choice//[[:space:]]/}"
        if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#TIMEZONE_CHOICES[@]} )); then
            break
        fi
        echo "Invalid selection - please type a number between 1 and ${#TIMEZONE_CHOICES[@]}."
        done

        SELECTED_TZ="${TIMEZONE_CHOICES[$((choice-1))]}"
        echo "You chose: $SELECTED_TZ"
        write_config "$SELECTED_TZ"
        exit 0
}
        
#-noninteractive mode
handle_noninteractive() {
    local input="${1}"
    if [[ "$input" =~ ^[0-9]+$ ]]; then
        if (( input >= 1 && input <= ${#TIMEZONE_CHOICES[@]} )); then
           SELECTED_TZ="${TIMEZONE_CHOICES[$((input-1))]}"
           write_config "$SELECTED_TZ"
           exit 0
        else 
           echo "Number $INPUT is out of range. Switching to interactive mode."
           run_interactive
        fi
        else
          if printf '%\n' "${TIMEZONE_CHOICES[@]}" | grep -Fxq "$input"; then 
              SELECTED_TZ="$input"
              write_config "$SELECTED_TZ"
              exit 0
        else
             echo " \"$input\" is not a supported timezone. Switching to interactive mode"
             run_interactive 
        fi
    fi
}
           
#setting up service and files
SCRIPT_SRC="./ProtonVPN/Linux/system/vpntime.sh"
SCRIPT_DST="/usr/local/bin/vpntime.sh"
install -m 755 "$SCRIPT_SRC" "$SCRIPT_DST"

SERVICE_SRC="./ProtonVPN/Linux/system/vpntime.service"
SERVICE_DST="/etc/systemd/system/vpntime.service"
install -m 644 "$SERVICE_SRC" "$SERVICE_DST"

TRIGBOOT_SRC="./ProtonVPN/Linux/trigger/timeboot.service"
TRIGBOOT_DST="/etc/systemd/system/timeboot.service"
install -m 644 "$TRIGBOOT_SRC" "$TRIGBOOT_DST"

TRIGGER_SRC="./ProtonVPN/Linux/trigger/vpn-tz@.service"
TRIGGER_DST="/etc/systemd/system/vpn-tz@.service"
systemctl daemon-reload
systemctl enable vpntime.service
systemctl enable timeboot.service

#get vpn interface name from user
read -rp "Enter the name of the VPN interface you will use. (e.g. tun0, wg0, proton0): " IFACE
sudo systemctl enable "vpn-tz@${IFACE}.service"
echo "Enabled vpn‑tz@${IFACE}.service"

 #closing status and RTC check
typewriter "Installation completed successfully."
typewriter "The service has been enabled."

 ########-block K - NTP sync check-########
 
if ! timedatectl show | grep NTPSynchronized=yes; then
    timedatectl set-ntp true
    typewriter "NTP was updated to ensure accurate system time."
fi

typewriter "The system's timezone will sync with the ip address' geolocation as soon as vpn connection is established."
typewriter "A slight delay might occur between system settings and GUI. "
